from __future__ import annotations

import json
from pathlib import Path

import jsonschema
import pytest


ROOT = Path(__file__).resolve().parents[1]


def load_json(path: str) -> dict:
    return json.loads((ROOT / path).read_text(encoding="utf-8"))


def test_skill_md_keeps_coding_agent_safety_invariants() -> None:
    skill_text = (ROOT / "skill.md").read_text(encoding="utf-8").lower()

    required_phrases = [
        "never execute arbitrary shell commands generated by the llm",
        "only render reviewed command templates declared in the capsule",
        "always check environment requirements before execution",
        "always run smoke tests when available",
        "always write a run record",
        "always report known failure cases",
        "always fail closed when required metadata is missing",
        "do not claim reproducibility beyond the verified environment matrix",
        "do not download model weights without showing source, license, and checksum status",
    ]

    for phrase in required_phrases:
        assert phrase in skill_text


def test_missing_manifest_fails_skill_input_schema() -> None:
    schema = load_json("schemas/skill-input.schema.json")
    data = load_json("tests/fixtures/invalid_missing_manifest.json")
    with pytest.raises(jsonschema.ValidationError):
        jsonschema.validate(data, schema)


def test_arbitrary_shell_is_rejected() -> None:
    schema = load_json("schemas/execution-request.schema.json")
    data = load_json("tests/fixtures/invalid_arbitrary_shell.json")
    with pytest.raises(jsonschema.ValidationError):
        jsonschema.validate(data, schema)


def test_reviewed_wrapper_without_review_metadata_is_rejected() -> None:
    schema = load_json("schemas/execution-request.schema.json")
    data = load_json("tests/fixtures/invalid_unreviewed_wrapper.json")
    with pytest.raises(jsonschema.ValidationError):
        jsonschema.validate(data, schema)


def missing_required_inputs(input_files: list[dict], workflow_inputs: list[dict]) -> list[str]:
    provided = {item["name"] for item in input_files}
    return [
        item["name"]
        for item in workflow_inputs
        if item.get("required", False) and item["name"] not in provided
    ]


def test_optional_input_missing_is_not_a_refusal_case() -> None:
    input_files = [
        { "name": "structure_or_tpr", "path": "inputs/topol.tpr" },
        { "name": "trajectory", "path": "inputs/traj.xtc" }
    ]
    workflow_inputs = [
        { "name": "structure_or_tpr", "required": True },
        { "name": "trajectory", "required": True },
        { "name": "index_file", "required": False }
    ]
    assert missing_required_inputs(input_files, workflow_inputs) == []


def test_missing_required_input_remains_a_refusal_case() -> None:
    input_files = [
        { "name": "structure_or_tpr", "path": "inputs/topol.tpr" }
    ]
    workflow_inputs = [
        { "name": "structure_or_tpr", "required": True },
        { "name": "trajectory", "required": True },
        { "name": "index_file", "required": False }
    ]
    assert missing_required_inputs(input_files, workflow_inputs) == ["trajectory"]


def test_refusal_output_can_explain_missing_metadata() -> None:
    schema = load_json("schemas/skill-output.schema.json")
    output = {
        "parsed_task": {"task_type": "protein-ligand-docking"},
        "selected_workflow": None,
        "selected_manifests": [],
        "readiness_checks": [],
        "missing_requirements": ["model weight checksum", "model weight license"],
        "proposed_execution_plan": None,
        "approval_required": False,
        "refusal": {
            "refused": True,
            "reason": "Required model-weight metadata is missing.",
            "safe_next_action": "Record model-weight source, license, and checksum before execution."
        },
        "warnings": ["No execution was attempted."],
        "expected_outputs": [],
        "run_record_template": None
    }
    jsonschema.validate(output, schema)
